language: rust

sudo: required

rust:
  - nightly

before_install:
  - |
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz &&
    cd SDL2-2.0.8 &&
    ./configure &&
    make &&
    sudo make install

before_script:
  - rustup install nightly
  - rustup component add clippy-preview --toolchain nightly
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - cargo +nightly clippy --all-targets
  - cargo +nightly fmt --verbose --all -- --check
  - cargo build --verbose --all
