language: rust

sudo: required

rust:
  - nightly

before_script:
  - rustup install nightly
  - rustup component add clippy-preview --toolchain nightly
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - cargo +nightly clippy --all-targets --features sdl2
  - cargo +nightly fmt --verbose --all -- --check
  - cargo build --verbose --all
