language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - |
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz &&
    cd SDL2-2.0.8 &&
    ./configure &&
    make &&
    sudo make install

before_script:
  - rustup install nightly-2018-12-06
  - rustup component add clippy-preview --toolchain nightly-2018-12-06
  - rustup component add rustfmt-preview --toolchain nightly-2018-12-06

script:
  - cargo build --verbose --all-targets
  - cargo +nightly-2018-12-06 fmt --verbose --all -- --verbose --check
  - cargo +nightly-2018-12-06 clippy --verbose --all-targets
