language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - |
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz &&
    cd SDL2-2.0.8 &&
    ./configure &&
    make &&
    sudo make install

before_script:
  - rustup install stable
  - rustup component add clippy --toolchain stable
  - rustup component add rustfmt --toolchain stable

script:
  - cargo build --verbose --all-targets
  - cargo +stable fmt --verbose --all -- --verbose --check
  - cargo +stable clippy --verbose --all-targets
